#!/bin/bash

GUROBI_HOME_TMP=$HOME/Software/gurobi702/linux64
append_to_env PATH $GUROBI_HOME_TMP/bin
append_to_env LD_LIBRARY_PATH $GUROBI_HOME_TMP/lib
append_to_env PYTHONPATH $GUROBI_HOME_TMP/lib/python2.7
append_to_env GUROBI_HOME $HOME_TMP/Software/gurobi702/linux64
