#!/bin/bash

source_robotpkg_workspace(){
    add_to_env PATH /opt/openrobots/bin
    add_to_env PKG_CONFIG_PATH /opt/openrobots/lib/pkgconfig
    add_to_env LD_LIBRARY_PATH /opt/openrobots/lib
    add_to_env PYTHONPATH /opt/openrobots/lib/python2.7/site-packages
    add_to_env ROS_PACKAGE_PATH /opt/openrobots/share
}
alias sourcerobotpkgworkspace='source_robotpkg_workspace'

sourcerobotpkgworkspace

