#!bin/bash

sudo apt-get purge robotpkg-* -y
sudo rm -fr /opt/openrobots
sudo apt-get install robotpkg-dynamic-graph-v3                `# 4.2.1     amd64  Efficient data-flow C++ library for robotics` \
                     robotpkg-eigen-quadprog                  `# 1.0.0r1   amd64  QuadProg QP solver using the Eigen3 library` \
                     robotpkg-example-robot-data              `# 3.4.2     amd64  Robot URDFs for benchmarking and developed examples` \
                     robotpkg-hpp-fcl                         `# 1.4.5     amd64  Humanoid Path Planner (collision detection and distance computations)` \
                     robotpkg-libccd                          `# 2.0       amd64  collision detection` \
                     robotpkg-octomap                         `# 1.9.0     amd64  An Efficient Probabilistic 3D Mapping Framework Based on Octrees` \
                     robotpkg-pinocchio                       `# 2.4.6     amd64  Efficient rigid body dynamics` \
                     robotpkg-sot-core-v3                     `# 4.9.1     amd64  Hierarchical task based control of humanoid robots` \
		     robotpkg-py35-crocoddyl                  `# 1.3.0     amd64  Optimal control library for robot under contact sequence` \
                     robotpkg-py35-dynamic-graph-v3           `# 3.5.2     amd64  Efficient data-flow C++ library for robotics (python bindings)` \
                     robotpkg-py35-eigenpy                    `# 2.4.0     amd64  Eigen bindings to python` \
                     robotpkg-py35-example-robot-data         `# 3.4.2     amd64  Robot URDFs for benchmarking and developed examples` \
                     robotpkg-py35-hpp-fcl                    `# 1.4.5     amd64  Humanoid Path Planner (collision detection and distance computations (python bindingss))` \
                     robotpkg-py35-pinocchio                  `# 2.4.6     amd64  Efficient rigid body dynamics (python bindings)` \
                     robotpkg-py35-quadprog                   `# 0.1.6r1   amd64  Solve a strictly convex quadratic program` \
                     robotpkg-py35-sot-core-v3                `# 4.9.1     amd64  Hierarchical task based control of humanoid robots (python bindings)` \
		     robotpkg-py35-tsid                       `# -----     amd64  inverse dynamics`

#                     robotpkg-sot-tools-v3                    `# 2.2.2     amd64  tools for the sot-core package`
#                     robotpkg-sot-dynamic-pinocchio-v3        `# 3.5.2     amd64  Create entities to compute a robot dynamics properties using pinocchio`
#                     robotpkg-py35-sot-dynamic-pinocchio-v3   `# 3.5.2     amd64  Create entities to compute a robot dynamics properties using pinocchio (python bindings)`
#                     robotpkg-py35-sot-tools-v3               `# 2.2.2     amd64  tools for the sot-core package (python bindings)`
